### PR TITLE
fixed decelerating to be set to 0 when velocity is lower than 0

### LINKED ISSUE #1: As a pilot, I want my braking force to slow down my car no matter where I'm pointing

### PR DESCRIPTION
**Pull request by Olivier-Gauvin**

### CODE REVIEW

File: Assets/Scripts/CarController.cs [hunk 1]
```diff
@@ -78,7 +78,15 @@ private void Decelerate()
     {
         //todo1: fix exploit of breaking being faster than going forward.
         //todo1-notes: breaking should not take into account direction of vehicle, only direction of inertia
-        _rb.AddForce(new Vector2(BrakingPower * -xModifier * Time.deltaTime, BrakingPower * -yModifier * Time.deltaTime));
+        if (_rb.velocity.y > 0)
```
Comment (patatos12321) [inline Assets/Scripts/CarController.cs:81]: This will only work until the car turns. If the car is pointing downards but the ymodifier is negative, then braking should check for the opposite conditon to detect going into reverse. And then! Same for left and right.

It's way outside the scope of your item. I'm going to update your code to use the same logic for the 4 axis.

**Review by patatos12321 — APPROVED** [review]
Great job, tested on my machine and it works great! 🤓
